### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by sebmck** [babel-plugins/babel-plugin-flow-comments#1]
Not sure how these should be converted to comments.

```javascript
function foo(bar?) {}
```

**Comment by samwgoldman** [comment]
Optional parameters are equivalent to `void | T` for some `T`.

It's possible that the comment syntax can support optional params—@jeffmo?—but if not, the following should work:

```javascript
function foo(bar?: string) {}
```

```javascript
function foo(bar /*: void | string */) {}
```

**Comment by jeffmo** [comment]
It doesn't dovetail quite as nicely as the other syntax, but it should be possible to do:

function foo(bar/*::?: string */) {}

(Double-colon is the escape-hatch for non-colon-prefixed annotations)

**Comment by hzoo** [comment]
If that's the case seems to easy to add? - `if (parent.optional) comment = "?" + comment;` Added it to my pr and test case

**Comment by hzoo** [comment]
Ah actually that fix only did it for `function foo(bar?: string) {}` not `function foo(bar?) {}` so will do another PR for that

**Comment by samwgoldman** [comment]
Interesting. I didn't realize that syntax worked, but it does. FWIW, the comment style is `function foo(bar /* ::? */) {}`

**Comment by hzoo** [comment]
Ok I just did a PR - is the whitespace significant because my test is a bit different?

**Comment by samwgoldman** [comment]
Cool. Whitespace is insignificant in my tests.
