### ISSUE TITLE
Preserve /*@flow*/ and import type statements

### ISSUE THREAD

**Issue by gaearon** [babel-plugins/babel-plugin-flow-comments#10]
Currently, even with the plugin, `/* @flow */` is stripped, so I can't use this as is for publishing a Flow-enabled module on NPM.

Another issue is that `import type` does not seem to be preserved. It needs to be wrapped into `/*:: */` in order for the references to make sense.

#### Source

```js
/* @flow */

import type { Stuff } from './types';

function lol(x: Stuff) {
}
```

#### Actual output

```js
'use strict';

function lol(x /*: Stuff*/) {}
```

#### Expected output

```js
/* @flow */

'use strict';

/*::
  import type { Stuff } from './types';
*/

function lol(x /*: Stuff*/) {}
```

**Comment by sebmck** [comment]
Blacklist the `flow` transformer to prevent the removal of `@flow` comments.
