### ISSUE TITLE
Type casts are handled incorrectly

### ISSUE THREAD

**Issue by zpao** [babel-plugins/babel-plugin-flow-comments#14]
I'm trying to use this on the fbjs codebase (https://github.com/facebook/fbjs/pull/17) as we add more types to our open source code, however it doesn't handle `TypeCastExpression`s well (that's my best guess but I could be wrong). I tried to fix this myself but couldn't so just filing an issue.

## fixture:
```js
var a = (y:any);
```

## expected (I think):
```js
var a = (y /*: any*/);
```
or maybe
```js
var a = y /*: any */;
```

## actual:
```js
var a = /*:: y: any*/;
```

cc @yungsters

**Comment by sebmck** [comment]
Attached patch implements the first expected behaviour. I'll confirm that it works in flow and publish if it works correctly.

**Comment by sebmck** [comment]
Confirmed that it works.

```
$ cat index.js
/* @flow */

function foo() {
  return "foo";
}

var a = (foo() /*: number*/);
$ flow check

/Users/sebastian/Scratch/flow-test/index.js:4:10,14: string
This type is incompatible with
  /Users/sebastian/Scratch/flow-test/index.js:7:20,25: number

Found 1 error
```

Published as of 1.0.7, thanks!

**Comment by hzoo** [comment]
@sebmck I don't see the 1.0.7 commit (similar to before?) - can you see if you can push that?

**Comment by sebmck** [comment]
@hzoo Done 9b43e2f55ade23aa9f8c0a8243d93e4633260ea2. I think there's something wrong with my git because this should be happening whenever `babel-plugin publish` is ran.
