### ISSUE TITLE
Comments in type declarations break

### ISSUE THREAD

**Issue by sebmck** [babel-plugins/babel-plugin-flow-comments#2]
@ide

> Comments in the type declarations are not escaped. For example:
> ```js
> type CustomType = {
> /** This is some documentation. */
> name: string;
> };
> ```
> is emitted as:
> ```js
> /*:: type CustomType = {
> /** This is some documentation. */
> name: string;
> };*/
> ```

**Comment by hzoo** [comment]
Can we just do something like `this.getSource().replace("*/","//");`?
